server:
  port: 8108
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.74.128
  rabbitmq:
    username: leyou
    password: leyou
    host: 192.168.74.128
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: D:\\upload\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN