server:
  port: 9086

spring:
  application:
    name: leyou-registry

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9086/eureka
    register-with-eureka: false
    fetch-registry: false